// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/recomendation.proto

package recommendation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        uint32                 `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Budget        float64                `protobuf:"fixed64,3,opt,name=budget,proto3" json:"budget,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Activities    []string               `protobuf:"bytes,6,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripInfo) Reset() {
	*x = TripInfo{}
	mi := &file_proto_recomendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripInfo) ProtoMessage() {}

func (x *TripInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripInfo.ProtoReflect.Descriptor instead.
func (*TripInfo) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{0}
}

func (x *TripInfo) GetTripId() uint32 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *TripInfo) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TripInfo) GetBudget() float64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *TripInfo) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TripInfo) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *TripInfo) GetActivities() []string {
	if x != nil {
		return x.Activities
	}
	return nil
}

type UserTripHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PastTrips     []*TripInfo            `protobuf:"bytes,2,rep,name=past_trips,json=pastTrips,proto3" json:"past_trips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTripHistory) Reset() {
	*x = UserTripHistory{}
	mi := &file_proto_recomendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTripHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTripHistory) ProtoMessage() {}

func (x *UserTripHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTripHistory.ProtoReflect.Descriptor instead.
func (*UserTripHistory) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{1}
}

func (x *UserTripHistory) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserTripHistory) GetPastTrips() []*TripInfo {
	if x != nil {
		return x.PastTrips
	}
	return nil
}

type RecommendationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreferredDestination string                 `protobuf:"bytes,2,opt,name=preferred_destination,json=preferredDestination,proto3" json:"preferred_destination,omitempty"`
	MaxBudget            float64                `protobuf:"fixed64,3,opt,name=max_budget,json=maxBudget,proto3" json:"max_budget,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	mi := &file_proto_recomendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendationRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecommendationRequest) GetPreferredDestination() string {
	if x != nil {
		return x.PreferredDestination
	}
	return ""
}

func (x *RecommendationRequest) GetMaxBudget() float64 {
	if x != nil {
		return x.MaxBudget
	}
	return 0
}

type Recommendation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Destination         string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	EstimatedBudget     float64                `protobuf:"fixed64,3,opt,name=estimated_budget,json=estimatedBudget,proto3" json:"estimated_budget,omitempty"`
	SuggestedActivities []string               `protobuf:"bytes,4,rep,name=suggested_activities,json=suggestedActivities,proto3" json:"suggested_activities,omitempty"`
	BestSeason          string                 `protobuf:"bytes,5,opt,name=best_season,json=bestSeason,proto3" json:"best_season,omitempty"`
	MatchScore          float64                `protobuf:"fixed64,6,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_proto_recomendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{3}
}

func (x *Recommendation) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Recommendation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recommendation) GetEstimatedBudget() float64 {
	if x != nil {
		return x.EstimatedBudget
	}
	return 0
}

func (x *Recommendation) GetSuggestedActivities() []string {
	if x != nil {
		return x.SuggestedActivities
	}
	return nil
}

func (x *Recommendation) GetBestSeason() string {
	if x != nil {
		return x.BestSeason
	}
	return ""
}

func (x *Recommendation) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

type RecommendationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendationResponse) Reset() {
	*x = RecommendationResponse{}
	mi := &file_proto_recomendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResponse) ProtoMessage() {}

func (x *RecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResponse.ProtoReflect.Descriptor instead.
func (*RecommendationResponse) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendationResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *RecommendationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BudgetAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        uint32                 `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	TotalBudget   float64                `protobuf:"fixed64,2,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	Expenses      []*Expense             `protobuf:"bytes,3,rep,name=expenses,proto3" json:"expenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetAnalysisRequest) Reset() {
	*x = BudgetAnalysisRequest{}
	mi := &file_proto_recomendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetAnalysisRequest) ProtoMessage() {}

func (x *BudgetAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetAnalysisRequest.ProtoReflect.Descriptor instead.
func (*BudgetAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{5}
}

func (x *BudgetAnalysisRequest) GetTripId() uint32 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *BudgetAnalysisRequest) GetTotalBudget() float64 {
	if x != nil {
		return x.TotalBudget
	}
	return 0
}

func (x *BudgetAnalysisRequest) GetExpenses() []*Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

type Expense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_proto_recomendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expense.ProtoReflect.Descriptor instead.
func (*Expense) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{6}
}

func (x *Expense) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Expense) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Expense) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CategoryAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	TotalSpent    float64                `protobuf:"fixed64,2,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryAnalysis) Reset() {
	*x = CategoryAnalysis{}
	mi := &file_proto_recomendation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryAnalysis) ProtoMessage() {}

func (x *CategoryAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryAnalysis.ProtoReflect.Descriptor instead.
func (*CategoryAnalysis) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{7}
}

func (x *CategoryAnalysis) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryAnalysis) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *CategoryAnalysis) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *CategoryAnalysis) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BudgetAnalysisResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalBudget       float64                `protobuf:"fixed64,1,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	TotalSpent        float64                `protobuf:"fixed64,2,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	Remaining         float64                `protobuf:"fixed64,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	CategoryBreakdown []*CategoryAnalysis    `protobuf:"bytes,4,rep,name=category_breakdown,json=categoryBreakdown,proto3" json:"category_breakdown,omitempty"`
	Warnings          []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Suggestions       []string               `protobuf:"bytes,6,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BudgetAnalysisResponse) Reset() {
	*x = BudgetAnalysisResponse{}
	mi := &file_proto_recomendation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetAnalysisResponse) ProtoMessage() {}

func (x *BudgetAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recomendation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetAnalysisResponse.ProtoReflect.Descriptor instead.
func (*BudgetAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_recomendation_proto_rawDescGZIP(), []int{8}
}

func (x *BudgetAnalysisResponse) GetTotalBudget() float64 {
	if x != nil {
		return x.TotalBudget
	}
	return 0
}

func (x *BudgetAnalysisResponse) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *BudgetAnalysisResponse) GetRemaining() float64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *BudgetAnalysisResponse) GetCategoryBreakdown() []*CategoryAnalysis {
	if x != nil {
		return x.CategoryBreakdown
	}
	return nil
}

func (x *BudgetAnalysisResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *BudgetAnalysisResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_proto_recomendation_proto protoreflect.FileDescriptor

const file_proto_recomendation_proto_rawDesc = "" +
	"\n" +
	"\x19proto/recomendation.proto\x12\x0erecommendation\"\xb7\x01\n" +
	"\bTripInfo\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\rR\x06tripId\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06budget\x18\x03 \x01(\x01R\x06budget\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1e\n" +
	"\n" +
	"activities\x18\x06 \x03(\tR\n" +
	"activities\"c\n" +
	"\x0fUserTripHistory\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x127\n" +
	"\n" +
	"past_trips\x18\x02 \x03(\v2\x18.recommendation.TripInfoR\tpastTrips\"\x84\x01\n" +
	"\x15RecommendationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x123\n" +
	"\x15preferred_destination\x18\x02 \x01(\tR\x14preferredDestination\x12\x1d\n" +
	"\n" +
	"max_budget\x18\x03 \x01(\x01R\tmaxBudget\"\xf4\x01\n" +
	"\x0eRecommendation\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x10estimated_budget\x18\x03 \x01(\x01R\x0festimatedBudget\x121\n" +
	"\x14suggested_activities\x18\x04 \x03(\tR\x13suggestedActivities\x12\x1f\n" +
	"\vbest_season\x18\x05 \x01(\tR\n" +
	"bestSeason\x12\x1f\n" +
	"\vmatch_score\x18\x06 \x01(\x01R\n" +
	"matchScore\"|\n" +
	"\x16RecommendationResponse\x12H\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1e.recommendation.RecommendationR\x0frecommendations\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x01\n" +
	"\x15BudgetAnalysisRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\rR\x06tripId\x12!\n" +
	"\ftotal_budget\x18\x02 \x01(\x01R\vtotalBudget\x123\n" +
	"\bexpenses\x18\x03 \x03(\v2\x17.recommendation.ExpenseR\bexpenses\"Y\n" +
	"\aExpense\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\x87\x01\n" +
	"\x10CategoryAnalysis\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1f\n" +
	"\vtotal_spent\x18\x02 \x01(\x01R\n" +
	"totalSpent\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x89\x02\n" +
	"\x16BudgetAnalysisResponse\x12!\n" +
	"\ftotal_budget\x18\x01 \x01(\x01R\vtotalBudget\x12\x1f\n" +
	"\vtotal_spent\x18\x02 \x01(\x01R\n" +
	"totalSpent\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x01R\tremaining\x12O\n" +
	"\x12category_breakdown\x18\x04 \x03(\v2 .recommendation.CategoryAnalysisR\x11categoryBreakdown\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12 \n" +
	"\vsuggestions\x18\x06 \x03(\tR\vsuggestions2\xe0\x01\n" +
	"\x15RecommendationService\x12e\n" +
	"\x12GetRecommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\"\x00\x12`\n" +
	"\rAnalyzeBudget\x12%.recommendation.BudgetAnalysisRequest\x1a&.recommendation.BudgetAnalysisResponse\"\x00B&Z$travel-platform/proto/recommendationb\x06proto3"

var (
	file_proto_recomendation_proto_rawDescOnce sync.Once
	file_proto_recomendation_proto_rawDescData []byte
)

func file_proto_recomendation_proto_rawDescGZIP() []byte {
	file_proto_recomendation_proto_rawDescOnce.Do(func() {
		file_proto_recomendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recomendation_proto_rawDesc), len(file_proto_recomendation_proto_rawDesc)))
	})
	return file_proto_recomendation_proto_rawDescData
}

var file_proto_recomendation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_recomendation_proto_goTypes = []any{
	(*TripInfo)(nil),               // 0: recommendation.TripInfo
	(*UserTripHistory)(nil),        // 1: recommendation.UserTripHistory
	(*RecommendationRequest)(nil),  // 2: recommendation.RecommendationRequest
	(*Recommendation)(nil),         // 3: recommendation.Recommendation
	(*RecommendationResponse)(nil), // 4: recommendation.RecommendationResponse
	(*BudgetAnalysisRequest)(nil),  // 5: recommendation.BudgetAnalysisRequest
	(*Expense)(nil),                // 6: recommendation.Expense
	(*CategoryAnalysis)(nil),       // 7: recommendation.CategoryAnalysis
	(*BudgetAnalysisResponse)(nil), // 8: recommendation.BudgetAnalysisResponse
}
var file_proto_recomendation_proto_depIdxs = []int32{
	0, // 0: recommendation.UserTripHistory.past_trips:type_name -> recommendation.TripInfo
	3, // 1: recommendation.RecommendationResponse.recommendations:type_name -> recommendation.Recommendation
	6, // 2: recommendation.BudgetAnalysisRequest.expenses:type_name -> recommendation.Expense
	7, // 3: recommendation.BudgetAnalysisResponse.category_breakdown:type_name -> recommendation.CategoryAnalysis
	2, // 4: recommendation.RecommendationService.GetRecommendations:input_type -> recommendation.RecommendationRequest
	5, // 5: recommendation.RecommendationService.AnalyzeBudget:input_type -> recommendation.BudgetAnalysisRequest
	4, // 6: recommendation.RecommendationService.GetRecommendations:output_type -> recommendation.RecommendationResponse
	8, // 7: recommendation.RecommendationService.AnalyzeBudget:output_type -> recommendation.BudgetAnalysisResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_recomendation_proto_init() }
func file_proto_recomendation_proto_init() {
	if File_proto_recomendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recomendation_proto_rawDesc), len(file_proto_recomendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recomendation_proto_goTypes,
		DependencyIndexes: file_proto_recomendation_proto_depIdxs,
		MessageInfos:      file_proto_recomendation_proto_msgTypes,
	}.Build()
	File_proto_recomendation_proto = out.File
	file_proto_recomendation_proto_goTypes = nil
	file_proto_recomendation_proto_depIdxs = nil
}
