package tests

import (
	"testing"
	"travel-platform/internal/models"
	"travel-platform/internal/services"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

func (m *MockUserRepository) CreateUser(user *models.User) error {
	args := m.Called(user)
	return args.Error(0)
}

func (m *MockUserRepository) GetUserByID(id uint) (*models.User, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*models.User), args.Error(1)
}

func (m *MockUserRepository) GetUserByEmail(email string) (*models.User, error) {
	args := m.Called(email)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*models.User), args.Error(1)
}

func (m *MockUserRepository) GetAllUsers() ([]models.User, error) {
	args := m.Called()
	return args.Get(0).([]models.User), args.Error(1)
}

func (m *MockUserRepository) UpdateUser(user *models.User) error {
	args := m.Called(user)
	return args.Error(0)
}

func (m *MockUserRepository) DeleteUser(id uint) error {
	args := m.Called(id)
	return args.Error(0)
}

func TestRegister_Success(t *testing.T) {
	mockRepo := new(MockUserRepository)
	service := services.NewUserService(mockRepo)

	email := "test@example.com"
	password := "password123"
	firstName := "Test"
	lastName := "User"

	// Step 1: Mock GetUserByEmail to return nil (user doesn't exist)
	mockRepo.On("GetUserByEmail", email).Return(nil, nil)

	// Step 2: Mock CreateUser to return nil (success)
	mockRepo.On("CreateUser", mock.AnythingOfType("*models.User")).Return(nil)

	user, err := service.Register(email, password, firstName, lastName)

	assert.NoError(t, err)
	assert.NotNil(t, user)
	assert.Equal(t, email, user.Email)
	assert.Equal(t, firstName, user.FirstName)
	mockRepo.AssertExpectations(t)
}

func TestRegister_UserAlreadyExists(t *testing.T) {
	mockRepo := new(MockUserRepository)
	service := services.NewUserService(mockRepo)

	email := "existing@example.com"
	existingUser := &models.User{Email: email}

	// Mock GetUserByEmail to return an existing user
	mockRepo.On("GetUserByEmail", email).Return(existingUser, nil)

	user, err := service.Register(email, "password", "First", "Last")

	assert.Error(t, err)
	assert.Nil(t, user)
	assert.Equal(t, "user with this email already exists", err.Error())
	mockRepo.AssertExpectations(t)
}
